### ISSUE TITLE
fix new game

### ISSUE THREAD

**Issue by okwme** [trifle-labs/anybody-problem#102]
new game works atm but it breaks the proof generation system. 

We need to listen from the front end for the new game event and either:  
- save the current proof generation because it's meant to be submitted while the user tries to beat their record
  - might require multiple `this.proofs` arrays in the component but probably not a good idea to attempt that
- discard it in order to make way for a new attempt
  - purge `this.proofs`
  - this means we need to also need to run `anybody.clearValues()` to make sure they're fresh but also `anybody.init()` to make sure original settings are used
- another scenario that will be more difficult is where the user beats the game and is expecting it to be loaded with the next harder level once the proof has been submitted but the delay between means that the screen is either paused for a long time or the user is busy doing something else

**Comment by okwme** [comment]
really what we want is a "retry" event to be emitted when the user loses the game (gameover) as well as when the user wins the game but wants to try again. This will purge the front end this.proofs array. If the user wins and wants to submit score, there should be another button/option that says "submit" or something. This moves the game state into something like a loading screen or mini-game until the front tells the anybody object that it's done and can go to new mode (maybe loads the new info at the same time)

**Comment by psugihara** [comment]
add 2 variables to anybody:
- inFrontend
- ownerIsPresent

on game win....

if ownerIsPresent:
- display a submit proof with score

else:

- FOMO: if you were the owner you would have been able to get this much dust

**Comment by okwme** [comment]
Win Scenario when owner is present:


SUCCESS

Bodies Included: 3
Bodies Boost: 3
Speed Boost: 2
Total Dust: 18
Claim Dust

Try Again



Win Scenario when owner is not present:

SUCCESS

Bodies Included: 3
Bodies Boost: 3
Speed Boost: 2
Total Dust: 18
If you owned this Problem you could claim this Dust

Try Again

**Comment by psugihara** [comment]
what is the thing I have done, lore-wise when I complete a problem?

e.g. 
SUCCESS: Level 1 Completed
Star level increased on all bodies.

or

SUCCESS: Problem Solved
Verify positions to claim dust

Trying to connect the text to narrative slightly.
