### ISSUE TITLE
score runoff and visuals on the music notes

### ISSUE THREAD

**Issue by okwme** [trifle-labs/anybody-problem#130]
<img width="810" alt="Screenshot 2024-05-01 at 17 41 24" src="https://github.com/trifle-labs/anybody-problem/assets/964052/bd608eff-7e20-4a6d-af53-0b8e15660c93">
<img width="949" alt="Screenshot 2024-05-01 at 17 37 50" src="https://github.com/trifle-labs/anybody-problem/assets/964052/ad149335-691a-4263-8a44-65ecb0b89204">

**Comment by psugihara** [comment]
lol
