### ISSUE TITLE
Mobile Play

### ISSUE THREAD

**Issue by okwme** [trifle-labs/anybody-problem#154]
This should be possible with a proving server. Think we should consider optimizing so that mobile play is possible. Would want to maybe drag finger for aiming, or something like a scroll up or down to point target differently?

**Comment by evvvritt** [comment]
until proving server, AP game should support a vertical mode and the mobile play is another context for practice mode that encourages play on desktop after (or bonus: export game to desktop)

![image](https://github.com/user-attachments/assets/13812b68-167c-4c0f-87f1-c26907a889fa)

**Comment by okwme** [comment]
hell yea
