### ISSUE TITLE
improve body mirroring on edges

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#192]
- [x] don't mirror baddies
- [ ] mirror hero body...
  - [ ] on just one dominant edge (most overlap?)
  - [ ] only mirror if hero is moving INTO that edge, and don't mirror the leaving edge once the core has jumped to the new edge (i've observed the background just sitting on the gun corner as it's leaving the gun area(
  - [ ] great if the mirrored body is like half transparent?
  - [ ] great if mirroed body is just the background

this reduces visual noise while still cluing the player

i was playing without any mirroring which was very performant and easy on the eyes, but missed hero mirroring

**Comment by okwme** [comment]
#207 and #204

**Comment by evvvritt** [comment]
removed altogether for performance
