### ISSUE TITLE
game: add practice mode, connect-wallet modal

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#198]
[figma design](https://www.figma.com/design/vXYzyaFjqw8BZDiLwHVnNX/anybody-problem?node-id=924-3992) (see comments of changes)

## Start screen
- if (wallet connected)
    - show PLAY button only
- else if (no wallet)
    - show PLAY + PRACTICE buttons
        - PLAY: opens Connect Wallet modal
            - CONNECT: sends message to parent app to connect wallet
        - PRACTICE: starts game

## Practice Solved screen
Similar to problem solved except
- no rank
- congratulations message
- different buttons
    - EXIT -> goes to title screen with PLAY/PRACTICE buttons

**Comment by okwme** [comment]
closed in #215
