### ISSUE TITLE
color: try baddies without transparent bg

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#199]
still darker than core but wonder if transparency isn't really consistent vibe

**Comment by evvvritt** [comment]
like, wonder when they mob the hero if better without transp

<img width="828" alt="Screenshot 2024-07-18 at 18 44 19" src="https://github.com/user-attachments/assets/02856d64-5830-47aa-b17d-f8afedb49eaf">

**Comment by okwme** [comment]
completed in #207 or #204
