### ISSUE TITLE
leaderboard time != game solved time

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#217]
<img width="2462" alt="Screenshot 2024-07-29 at 01 48 31" src="https://github.com/user-attachments/assets/d226ca4e-6fc5-4c1b-a2d6-0ca17b15fef8">

**Comment by evvvritt** [comment]
always off by 0.2
<img width="1695" alt="Screenshot 2024-07-29 at 02 14 55" src="https://github.com/user-attachments/assets/9a6b4cca-41e6-4129-b6f2-7ee8e040f634">

**Comment by okwme** [comment]
ah right, this is because the anybody.js runs one frame to generate the pause screen so the final number is one more than what the circuit finds. I'll figure out where it needs to be modified to do the cleanest fix...
