### ISSUE TITLE
shake screen effect can leave game offset from edges

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#233]
a bit hard to reproduce but at one point i noticed black margins left and top of the game area that I think are from skipping through the shake animation quickly?

**Comment by evvvritt** [comment]
(see right edge black offset)
<img width="768" alt="Screenshot 2024-08-04 at 20 51 54" src="https://github.com/user-attachments/assets/ef67f09f-b02d-43fc-ae25-2435a24e6dad">

**Comment by dataexcess** [comment]
@okwme Did you fix this?

**Comment by okwme** [comment]
I think so!
