### ISSUE TITLE
opensea iframe shows netlify not found?

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#261]
freshly minted, clicked 'view on opensea' link from mint modal

https://testnets.opensea.io/assets/base-sepolia/0xd28e9E8Ddcb512a0BF4bFCf80BCB802Bc2C109dc/1723334400

<img width="1650" alt="Screenshot 2024-08-12 at 00 10 50" src="https://github.com/user-attachments/assets/762b0ad8-53d4-4763-abe2-3a419e8b4772">

**Comment by okwme** [comment]
fixed, for some reason the index.html file wasn't built when someone pushed...
