### ISSUE TITLE
[minor] green dashes on stats should be darker purple

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#321]
<img width="1506" alt="Screenshot 2024-08-15 at 17 08 51" src="https://github.com/user-attachments/assets/e3f0d2a1-e4c0-42af-8801-0c960233fb9a">

**Comment by dataexcess** [comment]
Fixed in PR:

new color is: THEME.iris_30

https://github.com/trifle-labs/anybody-problem/pull/323
