### ISSUE TITLE
levels leaderboard wrong

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#349]
implemented on front end but definitely had a slower level than previous first place (level 3) but now it shows me winning all levels
<img width="393" alt="Screenshot 2024-09-20 at 12 59 18" src="https://github.com/user-attachments/assets/f375c82f-938b-4c7e-9c8b-a81a355b72d6">

**Comment by evvvritt** [comment]
(is this were we make API issues?)

**Comment by okwme** [comment]
#354
