### ISSUE TITLE
share: force copy-to-clipboard only (no navigator.share)

### ISSUE THREAD

**Issue by evvvritt** [trifle-labs/anybody-problem#351]
Latest Brave (and maybe Chrome?) on laptop trigger navigator.share on mac awkwardly (no option to copy the image), so perhaps detect those contexts and force copy-to-clipboard?

(TODO: bigger share improvements)

**Comment by okwme** [comment]
ah lol didn't see this issue. Made a new one [#148 ](https://github.com/trifle-labs/anybody-problem-frontend/issues/148) and closed here #357
