### ISSUE TITLE
Game Won Screen

### ISSUE THREAD

**Issue by okwme** [trifle-labs/anybody-problem#84]
## Game Won Screen
Similar to Game Lost Screen except for when the game is won. We should do more than pause the game. Proof generation will still be happening on the front end so would be good to either optimistically update state and assume the proofs will be fine and they will submit the transactions, or provide the user with some kind of mini-game or distraction / activity to occupy them until the proofs are done.

**Comment by okwme** [comment]
any ideas how to distract them while we finish generating the proof for them @psugihara @evvvritt ?

**Comment by psugihara** [comment]
(wouldn't be onchain at all, just front-end fun while you wait)

**Comment by okwme** [comment]
ja i like that, could actually impact score too if we make it a super simple game that coudl actually go on chain but only works if you also submit a completed game / just submitted a completed game

**Comment by okwme** [comment]
adding info from #90 

>Noticed that https://github.com/okwme/anybody-problem/pull/76 seems to have slightly unexpected behaviour. What I'm seeing is that at the moment the game ends the bodies turn into withering blobs at the point where the game ends. This is correct for game over but as https://github.com/okwme/anybody-problem/issues/84 is approached we should ensure that the bodies "final" position is actually when the proof is generated and not when the game is actually won. At the circuit and contract level the point that matters is when the proof is generated, so in the code this is when this.finalBatchSent is set to true (currently line 355 of anybody.js). Once that's set we should stop updating the positions.... Maybe this should also only happen to the bodies that are in fact turning into stars? As in the ones where starLvl == maxStarLvl.
